CREATE TABLE usuarios (
    id SERIAL PRIMARY KEY NOT NULL,
    nombre_completo VARCHAR(50) NOT NULL,
    correo VARCHAR(50) NOT NULL,
    usuario VARCHAR(50) NOT NULL,
    contrasena VARCHAR(250) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE chats (
    id SERIAL PRIMARY KEY NOT NULL,
    usuario_id INTEGER REFERENCES usuarios(id) NOT NULL,
    estado VARCHAR(20) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE mensajes (
    id SERIAL PRIMARY KEY NOT NULL,
    chat_id INTEGER REFERENCES chats(id) NOT NULL,
    emisor VARCHAR(50) NOT NULL,
    contenido TEXT NOT NULL,
    estilo VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);



